FROM ubuntu:16.04
MAINTAINER Siba Tripathy <tripathy.sibaprasad@gmail.com>

# Make sure the package repository is up to date.

#ENV http_proxy=http://ip:3128
#ENV https_proxy=http://ip:3128
RUN apt-get update
RUN apt-get install -y curl 
RUN curl -fsSL https://apt.dockerproject.org/gpg |  apt-key add -
#RUN apt-add-repository "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -cs) main"
#RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y git
# Install a basic SSH server
RUN apt-get install -y openssh-server
RUN sed -i 's|session    required     pam_loginuid.so|session    optional     pam_loginuid.so|g' /etc/pam.d/sshd
RUN mkdir -p /var/run/sshd

# Install JDK 7 (latest edition)
RUN apt-get install -y openjdk-8-jre

# Add user jenkins to the image
RUN adduser --quiet jenkins
# Set password for the jenkins user (you may want to alter this).
RUN echo "jenkins:jenkins" | chpasswd

RUN apt-get update && \
    apt-get install -y python-pip 
   

#RUN chown -R jenkins:jenkins /home/jenkins/ 
#RUN apt-get install -y pip
RUN pip install gitpython
RUN pip install gcg
RUN apt-get install -y maven
#RUN apt-get -y install docker
#RUN apt-get install docker-engine=1.13.1-0~ubuntu-xenial
RUN apt-get install docker.io -y
#RUN export DOCKER_API_VERSION=1.26
# Standard SSH port
EXPOSE 22

CMD ["/bin/bash"]
